### ISSUE TITLE
"index.json" is no longer kept up-to-date

### ISSUE THREAD

**Issue by mflint** [gianasista/tldr-viewer#5]
Hello,

`TldrApiClient`'s `LIST_URL` constant points to a URL which is no longer kept up-to-date by the "tldr-pages" maintainers.

Instead, they use their travis-ci build to recreate the index, then upload elsewhere. This URL might work better:

`https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/master/assets/index.json`

**Comment by gianasista** [comment]
Thank you for that hint!
